#!/bin/sh

setxkbmap fr oss &
tilda &

feh --bg-scale $HOME/.config/i3/officiel.png &

xautolock -detectsleep -time 15 -locker "~/.local/bin/lockscreen off" -locker "sudo pm-hibernate" -nowlocker "~/.local/bin/lockscreen" &

# Touchpad
synclient TapButton1=1
synclient ClickFinger2=3 TapButton2=3
synclient VertTwoFingerScroll=1
synclient PalmDetect=1
